# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

# Gateway backend configuration.
[backend]

# Backend type.
#
# Valid options are:
#   * semtech_udp
#   * concentratord
#   * basic_station
type="basic_station"

  # Basic Station backend.
  [backend.basic_station]

  # ip:port to bind the Websocket listener to.
  bind=":3001"

  # TLS certificate and key files.
  #
  # When set, the websocket listener will use TLS to secure the connections
  # between the gateways and ChirpStack Gateway Bridge (optional).
  tls_cert="-----BEGIN CERTIFICATE-----MIIDSDCCAjCgAwIBAgIUBvmUGD55aEspmlECBS2TODBCWT4wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UEAwwKY2hpcnBzdGFjazAeFw0yMzA2MTIxNjEyMTNaFw0zMzA2MDkxNjEyMTNaMBUxEzARBgNVBAMMCmNoaXJwc3RhY2swggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBr6j+xOSYaHu2dJs/TcOx1O0uYjw4l/aCAp8lmiXOeqxj5DS6MheXO/iqSkJCicHWPfc+j7YRhE+63w4BKdavWjtNchNmF8NZ//gP6Y5ZoIydvFcmE0xU4ZFYBTsW05Wjz8rTwiq2Yt92RmFQnKEVsqIYNvCgsOYGbaHrWn90SWAItxMUfxM6to44g3b3Th6qNT8xTH/yRbsnUtuZ1kqEw7cH2Ngs1B917pb08hvK+qwGJKxdjQI66za5X9/87hQw9nvKLO5qDv3svC2mgG8JqWB/buME4lBKHV6J8y56E6NQ0sbjbUTP82NR7bqLWoZtiudrZDLqGxjRlwUBSyNTAgMBAAGjgY8wgYwwHQYDVR0OBBYEFDBgPV6khcJcZAXe5Tom8iMOnfCpMFAGA1UdIwRJMEeAFDBgPV6khcJcZAXe5Tom8iMOnfCpoRmkFzAVMRMwEQYDVQQDDApjaGlycHN0YWNrghQG+ZQYPnloSymaUQIFLZM4MEJZPjAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEAD361rsoAKPx6Y/Ib6tUudaXIjoRJXMy5P4s43LoYvpvBwCVqQecrGfmr9K7gQd0qKa+dbcqODVJUjdbYWNlA0HUDPnsHYGxWsUMmrFmdktJCEuOhgezYTnbcETZWzJ+cJsnT2dkBHVO/waViOxm7w+9pwduY+kLx5R5PprayDe30ynjBhoWE7MxshrRLAmDCpncVuuSBhTDj/JCwMX5AyYeae53UcsQZD4EF3P+NJ64HVd4nd/j42WBTSfdInuzsL2v6VqWFmWiCYSSxKYVwHMuYEQnOcY1WRv+uQgGIJxKuGRmVi1g/qH7X0jJMXWRp0CtjYHbL1dNlciJ/UOnptA==-----END CERTIFICATE-----"
  tls_key="-----BEGIN PRIVATE KEY-----MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQD0Fdj0CXkkMpxQC/EyecWAYRKRJct+BwlcF+QJWXrvL6pnmF87naVSWQi1oJot0Eqkfyz7sXCNu6gOwmyXNcuHUbQaMnzREUCa0yCIwEZ1kJg/Xqni5BZgTptllQXfuilzICRTJG5y4g+kdfI2HU7T10Zj1sf1hMWohngpwltmyItTwD7FPbevp58UButRT5YCJl6uZxiWDyOeqJzlzvLte3TcYzfAP/R2ZzGJAMhc9SPAy/r/kCs6PrcilngGsezaIcnfh4NgAGci3a3is4VMOS1++ORF50jVoUqfTf7X+92vJogsxAgmkPVllHGFeAubmb4mIpuRpydF291GabaSVvQXX50CqHUdEd85+IlcRy7n30A4u4e6ldvS0i1dYyhCr4hl4YR2Mi8y5rPddrq+bZIinUTJ7XHROwCWdq14774ndPg8s+BbQmT6KGAXQs8qm0zO4bmlM/IFxI4Nt/8qWK9QQg6i67q4YGabMafQMIq/Y0I0jcsTHoPLkeBobt8gNZ8kwbOTOYqsMX5WXozQwL4nLLjUqXsJPgnz96iYm3+jHJMBpvt13K4gu+U7fCw4vWdoXso/Z5zBFgHJdpC0gKMKZf7+6fM9Rk7UzAkr7watlADx4iwJOnZDFplo7sKh0pDBb32eRl2mBH/6PvUXDs6aTGB+ysEzu24yPjWVTwIDAQABAoICADwoBkhe7VRWhN/VkaR3Do4NXp4XSofNBCmGWdVUEFBS1xShIRd4Sv54owTgiB8ybrMMBPIjUTIdRdYdZNX/lCHNqS2rs8dzEREXZ7VMbhEbiepUUlpxDHK/7NykVcZGA2E0Ur+LAw2dWW2XBBMCNiNPszF4BeAk0PIv8f2YwR4b3vrNLqs+Ar9v+GzfJ6/qhXYSLtOc5RpWsNixhbm9v3F4M9z9NwhSutVTqYmyf68pW55wp3PE/GJmgowruXks8Mrx+Ob2ZxKKBuE48VomFHwsu2HHxbrUvcao8dNBTcW9dW1tebJOvhODNnfKlg/m/jVjNtH/RYgoQi2denOYKj57p0S26FQus6MbU/IP7Xz+22px2M68vdbZN+aQuOkkxVQXOE+WV7zwRdqQv+82ZbC5iIEm3lC2Kt7TRtPpjFmeGnGG+54fgDh7EdKR6O7Lmv2i7Vd0GMK9zfgnKm5g5YK5ddQrg3ZSFlbK2RB4LVq2oS50YBMa2J0wSuaGG0Eas4GYVu23eqiRJ+e8pO4nS3K1CRnNZS+Y6oVD35AbPMhIdnJexj58KRf//Hzc4NJEMvmY6wf72c2U0lzY4N/7zwDQNceahBmqlIfwx3dzeaqyTtifLr+AskDFgcoAdJHOBMRpVFd+3ZzTrwqiZhTPH9RletXq3rl3oReJXFWbDwNBAoIBAQD8IYbwCNAIpf4+PfcbwVVM6MGlri1r5m6+KN2nHzLFZMQZAXIJtTIN2y29iBDr8m6qlObpxs17cworh9EZYt93+/1lzEeb5j0JWVkX4C1EBj50KWRhXIuoTEmba0VvOBR+po45E7FDhi0aroFEtyGBkqND5LfBPTY7ajfPfS6FpTcqPkEvsLjAyLktArn56sl8RxWfvGM8g83TDGCFoUXWa9Rb0gQyXXgw+tQyMj/AU74iXgjdUJJ2UYTQoXkhfxeECYcCF8fObh0qnykxa9EWrm0no29sUZXItjUfiHxraHQMDaKh+XAuE9JTYR1GGAXBLmvn5G/TVlELBpCWqCONAoIBAQD31LbBygluXJhwniH2BVF26EzQZ8/iAZqY9IOtJ+BZ01SL7vGU/8beKoNYLC4TAoZLyDCuDGJRWh4ywhJSw2KnPgyev9jE01GmTnzeXCWEZiEPQOvv0D+bW9h7QiPHIY9Wid+OoOPgDFX/22y0CyMEv3p/PvAi+D5g4SwGUl/7aWP5nmphD+mgb+YDJBPk7K3edhKWw/Chrdirc/CYfzdMg9mTGQePoZoegYSvxkURmmJTc1wZmfxWmrWwjfJNeiVuW4NitAzn0Oi9vXzFEsviNdf5oBkaJwMbfR1FkzvYlNi50hnOk5cwEIrC/MSLfgrApC9RAuZrA6/umZrxp5dLAoIBAQDSuVrEBzmH4OQrNTLwWZdnXilqxbZktgTcnd8TLHoMjHlwxMqA3pXlCsih3bT23nory6Nqw6M9iBp541uZsg8/grZ4fFFlNPrSc4CI+e4bKnTMNUQWM3jtwkTKxs8Tc3V9nMrFXXYMD3pnEG4t9jjkyJ/3wJLryLMo2U+n9OILBNikT7+/kh330ksiGWNCQz7+xZKHHLZ7/1TpDTEmvnFWEm08CL1FMuWfWiQ7h8/MeLEynBEgl5SxmtQ8YpiQrF4FFsllsGZoW5O46alOCuSH5mSIeopHp7BePhsMLdB/HJ/Q6xx/77AYcqyYz1PeH3m/yYKaH0xu/3dgla4GnKSJAoIBAQDqhwbn/szL/p5XvJ3A1qmQECdY9VS5uPDXHFVb0Kez+ZRB1D4T1bUZWzvufeigHrx+DJVcr+V+vPxk5lk2ryW1xLdmp4B4Ss4yxoXOW385eviAGdzslbMLz2/evOlksXKW32SK8eCTjrj3pmuJOhzKinVe422Wejt1rMDfvqaMIeD1QR/EeK2LITmW8VZORlgHdM8Ek6otJnorTk150rG/G+sTFBWeq7xQcBrjyIpmLSYteLbIl3s/barQyJNrFFNFyx5bkq2/1mfZ3u6rBK2ihXe8B/CZWh/LrKu9wqZYwAsUVioL3omtd4oJGfDZXM7KHNWWIVtyHAwqjHwfgYxfAoIBAQDauRsxQYbK6nl4jBkD70f0+VFZfcF8Re/KjKOGwNs2PtKRP2sEjeKkogha9jUKtHQRs8bCLdbmuVl9TtBlzY0pwIyNxLGLXTyr8f6E+DaGpvAGhnDYhAgbTx0WJbAuk+nLzY2eY8J9j3o0Vf2N+wT6R37mtnK3/G4RtscDScIK/4eheiVVF+jfnbtvOcbPMWTOnuTZFpi+3PO/a5j/+Mmzl7oKL7k2hA/nD0dKhUgLiav2a3wi8AF1F+dgjgse2PSqdc1sLvUyzJRdqonsIgTWNNmaIG2lRqyB03yWZ6JQVGQVLvKz8DLnkAQe+NkYQ7F9ZKRvAnq85c6qrtF6kPpu-----END PRIVATE KEY-----"

  # TLS CA certificate.
  #
  # When configured, ChirpStack Gateway Bridge will validate that the client
  # certificate of the gateway has been signed by this CA certificate.
  ca_cert="-----BEGIN CERTIFICATE-----MIIDSDCCAjCgAwIBAgIUBvmUGD55aEspmlECBS2TODBCWT4wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UEAwwKY2hpcnBzdGFjazAeFw0yMzA2MTIxNjEyMTNaFw0zMzA2MDkxNjEyMTNaMBUxEzARBgNVBAMMCmNoaXJwc3RhY2swggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBr6j+xOSYaHu2dJs/TcOx1O0uYjw4l/aCAp8lmiXOeqxj5DS6MheXO/iqSkJCicHWPfc+j7YRhE+63w4BKdavWjtNchNmF8NZ//gP6Y5ZoIydvFcmE0xU4ZFYBTsW05Wjz8rTwiq2Yt92RmFQnKEVsqIYNvCgsOYGbaHrWn90SWAItxMUfxM6to44g3b3Th6qNT8xTH/yRbsnUtuZ1kqEw7cH2Ngs1B917pb08hvK+qwGJKxdjQI66za5X9/87hQw9nvKLO5qDv3svC2mgG8JqWB/buME4lBKHV6J8y56E6NQ0sbjbUTP82NR7bqLWoZtiudrZDLqGxjRlwUBSyNTAgMBAAGjgY8wgYwwHQYDVR0OBBYEFDBgPV6khcJcZAXe5Tom8iMOnfCpMFAGA1UdIwRJMEeAFDBgPV6khcJcZAXe5Tom8iMOnfCpoRmkFzAVMRMwEQYDVQQDDApjaGlycHN0YWNrghQG+ZQYPnloSymaUQIFLZM4MEJZPjAMBgNVHRMEBTADAQH/MAsGA1UdDwQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEAD361rsoAKPx6Y/Ib6tUudaXIjoRJXMy5P4s43LoYvpvBwCVqQecrGfmr9K7gQd0qKa+dbcqODVJUjdbYWNlA0HUDPnsHYGxWsUMmrFmdktJCEuOhgezYTnbcETZWzJ+cJsnT2dkBHVO/waViOxm7w+9pwduY+kLx5R5PprayDe30ynjBhoWE7MxshrRLAmDCpncVuuSBhTDj/JCwMX5AyYeae53UcsQZD4EF3P+NJ64HVd4nd/j42WBTSfdInuzsL2v6VqWFmWiCYSSxKYVwHMuYEQnOcY1WRv+uQgGIJxKuGRmVi1g/qH7X0jJMXWRp0CtjYHbL1dNlciJ/UOnptA==-----END CERTIFICATE-----"

  # Stats interval.
  #
  # This defines the interval in which the ChirpStack Gateway Bridge forwards
  # the uplink / downlink statistics.
  stats_interval="30s"

  # Ping interval.
  ping_interval="1m0s"

  # Timesync interval.
  #
  # This defines the interval in which the ChirpStack Gateway Bridge sends
  # a timesync request to the gateway. Setting this to 0 disables sending
  # timesync requests.
  timesync_interval="1h0m0s"

  # Read timeout.
  #
  # This interval must be greater than the configured ping interval.
  read_timeout="1m5s"

  # Write timeout.
  write_timeout="1s"

  # Region.
  #
  # Please refer to the LoRaWAN Regional Parameters specification
  # for the complete list of common region names.
  region="US915"

  # Minimal frequency (Hz).
  frequency_min=902000000

  # Maximum frequency (Hz).
  frequency_max=928000000

  # Concentrator configuration.
  #
  # This section contains the configuration for the SX1301 concentrator chips.
  # Example:
  # [[backend.basic_station.concentrators]]
  #
  #   # Multi-SF channel configuration.
  #   [backend.basic_station.concentrators.multi_sf]
  #
  #   # Frequencies (Hz).
  #   frequencies=[
  #     868100000,
  #     868300000,
  #     868500000,
  #     867100000,
  #     867300000,
  #     867500000,
  #     867700000,
  #     867900000,
  #   ]
  #
  #   # LoRa STD channel.
  #   [backend.basic_station.concentrators.lora_std]
  #
  #   # Frequency (Hz).
  #   frequency=868300000
  #
  #   # Bandwidth (Hz).
  #   bandwidth=250000
  #
  #   # Spreading factor.
  #   spreading_factor=7
  #
  #   # FSK channel.
  #   [backend.basic_station.concentrators.fsk]
  #
  #   # Frequency (Hz).
  #   frequency=868800000

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

[integration.mqtt]
event_topic_template="us915/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="us915/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="us915/gateway/{{ .GatewayID }}/command/#"
